# Changes here will be overwritten by Copier.
_commit: 1.8.4
_src_path: gh:pawamoy/copier-uv
author_email: vandy.goel23@gmail.com
author_fullname: Vandit Goel
author_username: vandyG
copyright_date: '2025'
copyright_holder: Vandit Goel
copyright_holder_email: vandy.goel23@gmail.com
copyright_license: MIT
insiders: false
project_description: Fetch Event Details from Eventbrite.
project_name: eventbrite-cetd
python_package_command_line_name: eventbrite-cetd
python_package_distribution_name: eventbrite-cetd
python_package_import_name: eventbrite_cetd
repository_name: eventbrite-cetd
repository_namespace: vandyG
repository_provider: github.com

